name: "Spack"

on:
  # Always have a base image ready to go - this is a nightly build
  schedule:
    - cron: 0 3 * * *

  # Allow manual trigger of a build
  workflow_dispatch:

  # On push to main we build and deploy images
  push:
    branches:
      - master

  # Publish packages on release
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop      # Spack version (examples: develop, releases/v0.21)
          buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
          color: true       # Force color output (SPACK_COLOR=always)
          path: spack       # Where to clone Spack
      - name: Install MFEM MGIS
        run: |
          git clone https://github.com/rprat-pro/spack-repo-mfem-mgis.git
          spack repo add spack-repo-mfem-mgis
          spack install mmm+mpi+suite-sparse
