name: "Spack"

on:
  # Always have a base image ready to go - this is a nightly build
  schedule:
    - cron: 0 3 * * *

  # Allow manual trigger of a build
  workflow_dispatch:

  # On push to main we build and deploy images
  push:
    branches:
      - master

  # Publish packages on release
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        spack:
          - {version: v1.1.0, packages: releases/v2025.11}
          - {version: v1.2.2, packages: develop}
        mpi: ["+mpi", "~mpi"]
    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Spack
        uses: spack/setup-spack@v3
        with:
          spack_ref: ${{ matrix.spack.version }}      # Spack version
          packages_ref: ${{ matrix.spack.packages }}  # Spack packages (builtin repository) version
          buildcache: false # like users: its openblas+ilp64 breaks mumps~int64
          color: true       # Force color output (SPACK_COLOR=always)
          spack_path: spack # Where to clone Spack
      - name: Install MFEM MGIS
        run: |
          git clone https://github.com/rprat-pro/spack-repo-mfem-mgis.git
          spack repo add spack-repo-mfem-mgis
          spack install --test=root mfem-mgis${{ matrix.mpi }}
