name: Deploy Sphinx documentation to Pages

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master     

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: true
        documentation_path: docs/source
        requirements_path: docs/source/requirements.txt
