name: Deploy Sphinx documentation to Pages

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master     

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-doc-website
    permissions:
      pages: write
      id-token: write
      contents: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@3.2
      with:
        documentation_path: docs/source
        requirements_path: docs/source/requirements.txt
        publish: false
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}         
#        publish_branch: gh-pages
